.PHONY: build test run-backend run-proxy run-client

build:
	cargo build

test:
	cargo test

run-backend:
	cargo run --bin backend

run-proxy:
	cargo run --bin proxy

run-client:
	cargo run --bin client
