// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/math.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AddResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FibRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibRequest) Reset() {
	*x = FibRequest{}
	mi := &file_proto_math_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibRequest) ProtoMessage() {}

func (x *FibRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibRequest.ProtoReflect.Descriptor instead.
func (*FibRequest) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{2}
}

func (x *FibRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FibResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibResponse) Reset() {
	*x = FibResponse{}
	mi := &file_proto_math_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibResponse) ProtoMessage() {}

func (x *FibResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibResponse.ProtoReflect.Descriptor instead.
func (*FibResponse) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{3}
}

func (x *FibResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *FibResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_proto_math_proto protoreflect.FileDescriptor

const file_proto_math_proto_rawDesc = "" +
	"\n" +
	"\x10proto/math.proto\x12\tgrpcproxy\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"=\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\"\n" +
	"\n" +
	"FibRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\";\n" +
	"\vFibResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source2\x81\x01\n" +
	"\vMathService\x124\n" +
	"\x03Add\x12\x15.grpcproxy.AddRequest\x1a\x16.grpcproxy.AddResponse\x12<\n" +
	"\tFibonacci\x12\x15.grpcproxy.FibRequest\x1a\x16.grpcproxy.FibResponse0\x01B#Z!github.com/tordynnar/grpcproxy/pbb\x06proto3"

var (
	file_proto_math_proto_rawDescOnce sync.Once
	file_proto_math_proto_rawDescData []byte
)

func file_proto_math_proto_rawDescGZIP() []byte {
	file_proto_math_proto_rawDescOnce.Do(func() {
		file_proto_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_math_proto_rawDesc), len(file_proto_math_proto_rawDesc)))
	})
	return file_proto_math_proto_rawDescData
}

var file_proto_math_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_math_proto_goTypes = []any{
	(*AddRequest)(nil),  // 0: grpcproxy.AddRequest
	(*AddResponse)(nil), // 1: grpcproxy.AddResponse
	(*FibRequest)(nil),  // 2: grpcproxy.FibRequest
	(*FibResponse)(nil), // 3: grpcproxy.FibResponse
}
var file_proto_math_proto_depIdxs = []int32{
	0, // 0: grpcproxy.MathService.Add:input_type -> grpcproxy.AddRequest
	2, // 1: grpcproxy.MathService.Fibonacci:input_type -> grpcproxy.FibRequest
	1, // 2: grpcproxy.MathService.Add:output_type -> grpcproxy.AddResponse
	3, // 3: grpcproxy.MathService.Fibonacci:output_type -> grpcproxy.FibResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_math_proto_init() }
func file_proto_math_proto_init() {
	if File_proto_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_math_proto_rawDesc), len(file_proto_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_math_proto_goTypes,
		DependencyIndexes: file_proto_math_proto_depIdxs,
		MessageInfos:      file_proto_math_proto_msgTypes,
	}.Build()
	File_proto_math_proto = out.File
	file_proto_math_proto_goTypes = nil
	file_proto_math_proto_depIdxs = nil
}
